plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - BBC-BASIC-for-Agon.md
  - External-Documentation.md
  - FAQ.md
  - GPIO.md
  - MOS-API.md
  - MOS.md
  - Projects.md
  - Theory-of-operation.md
  - Third-Party-Projects.md
  - Updating-Firmware.md
  - VDP---Bitmaps-API.md
  - VDP---Buffered-Commands-API.md
  - VDP---Enhanced-Audio-API.md
  - VDP---PLOT-Commands.md
  - VDP---Screen-Modes.md
  - VDP---System-Commands.md
  - VDP---VDU-Commands.md
  - VDP.md
